^INC^Save for Subversion^^~Format=Cache.S~
%RO
csp^INC^^^0
 #define qt(%str) $tr(##class(%CSP.Page).QuoteJS(%str),"'","""")
 #define UNDERCONSTRUCTION &html<<div style="text-align:center;margin:10px 0px;padding:10px 0px;" class="ui-state-highlight"><img style="margin:0px auto" src="http://animatedgif.net/underconstruction/shhammer05_ss3_e0.gif" title="Страница на ремонте" alt="Страница на ремонте" /></div>>



